// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnBL8wvrthhRQKvPhgCDeshn3IGD_y0D4',
    appId: '1:347432761528:web:bc5294a613e932e6a25c4d',
    messagingSenderId: '347432761528',
    projectId: 'waterlevelmonitoring-ebe14',
    authDomain: 'waterlevelmonitoring-ebe14.firebaseapp.com',
    storageBucket: 'waterlevelmonitoring-ebe14.firebasestorage.app',
    measurementId: 'G-6XKTW0MEH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRw6cUHzctcnHgi0xg-JocSK-oQDYWk0',
    appId: '1:347432761528:android:a493f5f160dd991ba25c4d',
    messagingSenderId: '347432761528',
    projectId: 'waterlevelmonitoring-ebe14',
    storageBucket: 'waterlevelmonitoring-ebe14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjicgJvGGFywdw_iZbEU_R_hTh2S-ARHo',
    appId: '1:347432761528:ios:fd33b7bdf460a8c5a25c4d',
    messagingSenderId: '347432761528',
    projectId: 'waterlevelmonitoring-ebe14',
    storageBucket: 'waterlevelmonitoring-ebe14.firebasestorage.app',
    iosBundleId: 'com.example.waterLevelMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjicgJvGGFywdw_iZbEU_R_hTh2S-ARHo',
    appId: '1:347432761528:ios:fd33b7bdf460a8c5a25c4d',
    messagingSenderId: '347432761528',
    projectId: 'waterlevelmonitoring-ebe14',
    storageBucket: 'waterlevelmonitoring-ebe14.firebasestorage.app',
    iosBundleId: 'com.example.waterLevelMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnBL8wvrthhRQKvPhgCDeshn3IGD_y0D4',
    appId: '1:347432761528:web:9fdc3313d4f4c74ca25c4d',
    messagingSenderId: '347432761528',
    projectId: 'waterlevelmonitoring-ebe14',
    authDomain: 'waterlevelmonitoring-ebe14.firebaseapp.com',
    storageBucket: 'waterlevelmonitoring-ebe14.firebasestorage.app',
    measurementId: 'G-SV1TL3NHLJ',
  );
}
